sudo: false
language: perl
perl:
  - "blead"
  - "dev"
  - "5.28"
  - "5.24"
  - "5.22"
  - "5.18"
  - "5.14"
matrix:
  allow_failures:
    - perl: blead
    - perl: dev
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - [ -f 'Makefile.PL' ] && rm -v dist.ini
  - build-dist
  - cd $BUILD_DIR
install:
  - cpan-install --deps
script:
  - perl Makefile.PL
  - make
  - prove -b -r -s -j$(test-jobs) $(test-files)
