---
abstract: 'A straightforward and complete next-generation sequencing read simulator'
author:
  - 'Thiago L. A. Miller <tmiller@mochsl.org.br>'
  - 'J. Leonel Buzzo <lbuzzo@mochsl.org.br>'
  - 'Felipe R. C. dos Santos <fsantos@mochsl.org.br>'
  - 'Helena B. Conceição <hconceicao@mochsl.org.br>'
  - 'Gabriela Guardia <gguardia@mochsl.org.br>'
  - 'Fernanda Orpinelli <forpinelli@mochsl.org.br>'
  - 'Pedro A. F. Galante <pgalante@mochsl.org.br>'
build_requires:
  Class::Data::Inheritable: '0.08'
  Test::Class: '0.50'
  Test::Most: '0.35'
  Test::UseAllModules: '0'
  autodie: '0'
  perl: '5.014'
configure_requires:
  ExtUtils::MakeMaker: '0'
  File::ShareDir::Install: '0.03'
  perl: '5.004'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.150010'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-Sandy
requires:
  Carp: '0'
  Compress::BGZF::Writer: '0'
  DBIx::Class::Core: '0'
  DBIx::Class::Schema: '0'
  Data::OptList: '0'
  File::Cat: '0'
  File::Path: '0'
  Getopt::Long: '0'
  Hook::AfterRuntime: '0'
  IO::Compress::Gzip: '0'
  IO::Handle: '0'
  IO::Uncompress::Gunzip: '0'
  Import::Into: '0'
  List::Util: '1.44'
  Math::Random: '0.72'
  Module::Runtime: '0'
  Moose: '0'
  Moose::Role: '0'
  Moose::Util::TypeConstraints: '0'
  MooseX::Singleton: '0'
  MooseX::StrictConstructor: '0'
  MooseX::UndefTolerant: '0'
  Parallel::ForkManager: '1.19'
  Path::Class: '0'
  PerlIO::gzip: '0.19'
  Pod::Usage: '0'
  Scalar::Util: '0'
  Storable: '2.51'
  Text::ASCIITable: '0'
  Try::Tiny: '0'
  base: '0'
  constant: '0'
  feature: '0'
  namespace::autoclean: '0'
  perl: '5.014'
  strict: '0'
  'true': '0'
  utf8: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/galantelab/sandy/issues
  homepage: https://galantelab.github.io/sandy/
  repository: git://github.com/galantelab/sandy.git
version: '0.21'
x_generated_by_perl: v5.28.0
x_serialization_backend: 'YAML::Tiny version 1.73'
