---
abstract: 'Creates single-end and paired-end fastq reads for transcriptome and genome simulation'
author:
  - 'Thiago L. A. Miller <tmiller@mochsl.org.br>'
build_requires:
  Class::Data::Inheritable: '0.08'
  Test::Class: '0.50'
  Test::Most: '0.35'
  Test::UseAllModules: '0'
  autodie: '0'
  perl: '5.010'
configure_requires:
  ExtUtils::MakeMaker: '0'
  File::ShareDir::Install: '0.06'
  perl: '5.010'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.011, CPAN::Meta::Converter version 2.150010'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-SimulateReads
requires:
  Carp: '0'
  DBIx::Class::Core: '0'
  DBIx::Class::Schema: '0'
  Data::OptList: '0'
  File::Cat: '0'
  File::Path: '0'
  Getopt::Long: '0'
  Hook::AfterRuntime: '0'
  IO::Compress::Gzip: '0'
  IO::Uncompress::Gunzip: '0'
  Import::Into: '0'
  Math::Random: '0.72'
  Module::Runtime: '0'
  Moose: '0'
  Moose::Role: '0'
  Moose::Util::TypeConstraints: '0'
  MooseX::StrictConstructor: '0'
  MooseX::UndefTolerant: '0'
  Parallel::ForkManager: '1.19'
  Path::Class: '0'
  PerlIO::gzip: '0.19'
  Pod::Usage: '0'
  Scalar::Util: '0'
  Storable: '2.51'
  Try::Tiny: '0'
  base: '0'
  constant: '0'
  feature: '0'
  if: '0'
  namespace::autoclean: '0'
  perl: '5.010'
  strict: '0'
  'true': '0'
  utf8: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/galantelab/simulate_reads/issues
  repository: git://github.com/galantelab/simulate_reads.git
version: '0.14'
x_serialization_backend: 'YAML::Tiny version 1.70'
