#!/usr/bin/env perl

use strict;
use warnings;
use utf8;

use App::Sandy;

# PODNAME: Sandy
# ABSTRACT: A straightforward and complete next-generation sequencing read simulator

# VERSION

my $app = App::Sandy->new;
$app->run;
