#!/usr/bin/env perl 

use strict;
use warnings;
use utf8;

use App::Sandy;

# PODNAME: Sandy
# ABSTRACT: A straightforward and complete next-generation sequencing read simulator

our $VERSION = '0.18'; # VERSION

my $app = App::Sandy->new;
$app->run;

__END__

=pod

=encoding UTF-8

=head1 NAME

Sandy - A straightforward and complete next-generation sequencing read simulator

=head1 VERSION

version 0.18

=head1 SYNOPSIS

 $ sandy <command> ...

=head1 DESCRIPTION

B<Sandy> is a bioinformatic tool that provides a simple engine to generate
single-end/paired-end reads from a given fasta file. Many next-generation sequencing
(NGS) analyses rely on hypothetical models and principles that are not precisely
satisfied in practice. Simulated data, which provides positive controls would be a
perfect way to overcome these difficulties. Nevertheless, most of NGS simulators are
extremely complex to use, they do not cover all kinds of the desired features needed
by the users, and (some) are very slow to run in a standard computer. Here, we present
Sandy, a straightforward, easy to use, fast, complete set of tools to generate synthetic
next-generation sequencing reads. Sandy simulates whole genome sequencing, whole exome
sequencing, RNAseq reads and it presents several features to the users manipulate the data.
Sandy can be used therefore for benchmarking results of a variety of pipelines in the
genomics or trancriptomics.

=head1 INSTALLATION

=head2 PREREQUISITES

B<Sandy> uses the B<Comprehensive Perl Archive Network>, L<CPAN|https://www.cpan.org/>, as its
package manager, which allows a good control over all dependencies needed.
If you have Perl installed, then you may have the B<cpan> command utility. At the first run, cpan
will interactively configure your environment and mirror. In doubt, just confirm the default options
presented. After this, install cpanminus:

 % cpan -i App::cpanminus

App::cpanminus will provide the B<cpanm> utility, which has the capability of install not only
Sandy, but also all its dependencies recursively.

=head2 INSTALLING

Finally install B<Sandy>:

 % cpanm App::Sandy

For more details, see L<INSTALL|https://github.com/galantelab/sandy/blob/master/INSTALL> file

=head1 ACKNOWLEDGMENTS

I, Thiago L. A. Miller, would like to thank:

=over

=item Pedro A. F. Galante - for his guidance during my doctorate

=item Gabriela Guardia, Helena Conceição and Fernanda Orpinelli - for the advices and testing

=item J. Leonel Buzzo - for the documentation

=item L<Group of Bioinformatics of Teaching and Research Institute from Sírio-Libanês Hospital|https://www.bioinfo.mochsl.org.br/>

=back

=head1 AUTHORS

=over 4

=item *

Thiago L. A. Miller <tmiller@mochsl.org.br>

=item *

Gabriela Guardia <gguardia@mochsl.org.br>

=item *

J. Leonel Buzzo <lbuzzo@mochsl.org.br>

=item *

Fernanda Orpinelli <forpinelli@mochsl.org.br>

=item *

Pedro A. F. Galante <pgalante@mochsl.org.br>

=back

=head1 COPYRIGHT AND LICENSE

This software is Copyright (c) 2018 by Teaching and Research Institute from Sírio-Libanês Hospital.

This is free software, licensed under:

  The GNU General Public License, Version 3, June 2007

=cut
