#!/usr/bin/env perl

use strict;
use warnings;
use utf8;

use App::Sandy;

# PODNAME: Sandy
# ABSTRACT: A straightforward and complete next-generation sequencing read simulator

our $VERSION = '0.23'; # VERSION

my $app = App::Sandy->new;
$app->run;

__END__

=pod

=encoding UTF-8

=head1 NAME

Sandy - A straightforward and complete next-generation sequencing read simulator

=head1 VERSION

version 0.23

=head1 SYNOPSIS

 $ sandy <command> ...

=head1 DESCRIPTION

B<SANDY> is a bioinformatics tool that provides a simple engine to simulate next-generation
sequencing for genomic and transcriptomic data. Simulated data works as experimental control
- a key step to optimize NGS analysis - in comparison to hypothetical models. SANDY is a
straightforward, easy-to-use, fast and highly customizable tool that generates reads requiring
only a FASTA file as input. SANDY can simulate single/paired-end reads from both whole exome
sequencing and RNA-seq as if produced from the most used second and third-generation sequencing
platforms. SANDY’s reads can be simulated with genetic variations such as SNVs, indels and gene
fusions. For customization purposes, SANDY have built-in (native) databases that can be easily
extended with varying gene/transcript expression profiles, sequencing errors, sequencing
coverages and genomic variations.

=head1 INSTALLATION

B<Sandy> was designed for Linux based distributions. If you are working with another
type of operating system, such as macOS, Windows, try to use our docker image.
For more details, see L<docker/README.md|https://github.com/galantelab/sandy/blob/master/docker/README.md>
file.

=head2 PREREQUISITES

Along with B<Perl>, you must have B<zlib>, B<gcc> and B<make> packages installed:

=over 4

=item Debian/Ubuntu

 % apt-get install perl zlib1g-dev gcc make

=item CentOS/Fedora

 % yum install perl zlib gcc make

=item Archlinux

 % pacman -S perl zlib gcc make

=back

B<Sandy> uses the B<Comprehensive Perl Archive Network>, L<CPAN|https://www.cpan.org/>, as its
package manager, which allows a good control over all dependencies needed.
If you have Perl installed, then you may have the B<cpan> command utility. At the first run, cpan
will interactively configure your environment and mirror. In doubt, just confirm the default options
presented. After this, install cpanminus:

 % cpan -i App::cpanminus

App::cpanminus will provide the B<cpanm> utility, which has the capability of install not only
Sandy, but also all its dependencies recursively.

=head2 INSTALLING

Finally install B<Sandy>:

 % cpanm App::Sandy

In some cases, you may need to pass the flag '--force' to B<cpanm>:

 % cpanm --force App::Sandy

If you concern about speed, you can avoid testing with the flag '--notest':

 % cpanm --notest App::Sandy

For more details, see L<INSTALL|https://github.com/galantelab/sandy/blob/master/INSTALL> file

=head1 ACKNOWLEDGMENTS

=over 4

=item Coordination for the Improvement of Higher Level Personnel - L<CAPES|http://www.capes.gov.br/>

=item Teaching and Research Institute from Sírio-Libanês Hospital - L<Group of Bioinformatics|https://www.bioinfo.mochsl.org.br/>

=back

=head1 AUTHORS

=over 4

=item *

Thiago L. A. Miller <tmiller@mochsl.org.br>

=item *

J. Leonel Buzzo <lbuzzo@mochsl.org.br>

=item *

Felipe R. C. dos Santos <fsantos@mochsl.org.br>

=item *

Helena B. Conceição <hconceicao@mochsl.org.br>

=item *

Rodrigo Barreiro <rbarreiro@mochsl.org.br>

=item *

Gabriela Guardia <gguardia@mochsl.org.br>

=item *

Fernanda Orpinelli <forpinelli@mochsl.org.br>

=item *

Pedro A. F. Galante <pgalante@mochsl.org.br>

=back

=head1 COPYRIGHT AND LICENSE

This software is Copyright (c) 2018 by Teaching and Research Institute from Sírio-Libanês Hospital.

This is free software, licensed under:

  The GNU General Public License, Version 3, June 2007

=cut
