#!/usr/bin/env perl 

use strict;
use warnings;
use utf8;

use App::SimulateReads;

# PODNAME: simulate_reads
# ABSTRACT: Creates single-end and paired-end fastq reads for transcriptome and genome simulation.

my $app = App::SimulateReads->new;
$app->run;
