name: build

on:
  push:
    branches-ignore:
      - gh-pages
    paths-ignore:
      - docker/*
      - .github/workflows/docker.yml

jobs:
  perl:
    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1
      GITHUB_ACTIONS_CI: 1

    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - '5.36'
          - '5.34'
          - '5.32'
          - '5.30'
          - '5.28'
          - '5.26'
          - '5.24'
          - '5.22'
          - '5.20'

    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: perl -V
        run: perl -V

      - name: Install authordeps
        run: >
          dzil authordeps --missing
          | grep -v '^inc::'
          | cpanm --notest --quiet

      - name: Install deps
        run: >
          dzil listdeps --missing
          | cpanm --notest --quiet

      - name: Build and test App::Sandy
        run: dzil test --all
