name: deploy

on:
  push:
    branches:
      - master
      - dev
    tags:
      - '*.*.*'

jobs:
  docker:
    needs: test
    runs-on: ubuntu-20.04
    name: Build and deploy docker image
    steps:
      - name: Get release tag
        id: tag
        run: |
          case ${{ github.ref_name }} in
          master)
          echo name=latest >> $GITHUB_OUTPUT ;;
          *.*.*)
          echo name=release-${{ github.ref_name }} >> $GITHUB_OUTPUT ;;
          *)
          echo name=${{ github.ref_name }} >> $GITHUB_OUTPUT ;;
          esac

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: docker/Dockerfile
          tags: galantelab/sandy:${{ steps.tag.outputs.name }}

